name: swapi_planets
description: "Star Wars planets explorer — Yuki Flutter assessment."

publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^9.1.1

  # DI
  get_it: ^8.2.0

  # HTTP
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0

  # Code generation annotations
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Navigation
  go_router: ^16.2.5

  # UI
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
